BUCKET: nncpp-dev-dashboard-datasets
DATASET_METADATA_FILENAME: dataset-metadata.json
DATASETS:
- MOD13A1.006.json
- MOD13Q1_COGv1_NDVI_16D.json
- MOD13Q1_COGv1_EVI_16D.json
- OR_ABI_FDCF_Power.json
SITES:
- example
- noaa_example_fire_power